### ISSUE TITLE
missing 06_analyze_fl_analyze.ipynb

### ISSUE THREAD

**Issue by rootsmusic** [appeler/nc_race_ethnicity#1]
This script isn't wasn't uploaded.  By the way, where can I see the output of your NC evaluation?  Thanks.

**Comment by soodoku** [comment]
there are two evaluations: 

1. Model-based on FL data applied on NC Data is here: https://github.com/appeler/nc_race_ethnicity/blob/master/scripts/02_analyze_nc_voter.ipynb
2. Model based on NC data applied to FL Data. Missing as you pointed out. Added a script that cribs from above (need to think a bit more but should be fine): https://github.com/appeler/nc_race_ethnicity/blob/master/scripts/06_analyze_fl_analyze.ipynb
